// Generated by `npm run generate`, don't edit manually, edit src/generator/card_code.mst instead
import Card from "../card";

export default class CardFace extends Card {

	constructor(id) {
		super("{ \"cardCode\": \"face\" }", id);
	}
}